<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Client Name_basic_currentClient</name>
   <tag></tag>
   <elementGuidId>ebb0b750-2897-4c53-acc3-5febe5ceafe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_currentClient</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_currentClient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0607f14-9994-4ec1-8f7e-2c5c46938381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please choose client name</value>
      <webElementGuid>5e8fba67-2fb0-4021-8e28-e08c5cdd1bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_currentClient</value>
      <webElementGuid>69843f44-8f23-4bac-b71e-c6c7c45d02c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-disabled css-e8tju</value>
      <webElementGuid>b3a6305d-f6fb-4055-bcf2-d24aee21237b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f169b3f-1881-4215-9c93-0890e2831a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Automation-exe</value>
      <webElementGuid>7da514fc-9270-4e92-aebc-39a718c6761b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_currentClient&quot;)</value>
      <webElementGuid>93dbb6de-2ceb-4d30-9cc3-e0f493124a96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_currentClient']</value>
      <webElementGuid>8915aefe-6fd6-43a3-add3-4bb6bb6ab006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div/div[2]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>3e1f0091-cb45-4f76-b8d8-1ec3a905c763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>ec383799-7f5f-4fd7-82b6-e2d77e813e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please choose client name' and @id = 'basic_currentClient' and @type = 'text']</value>
      <webElementGuid>fd24f54b-0661-42f4-98eb-653dd73c8a4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
