<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Annual Leave Hours_basic_annualLeaveHours</name>
   <tag></tag>
   <elementGuidId>fac3b0a8-c6cb-4e8e-b256-ac5350bfba11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_annualLeaveHours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_annualLeaveHours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e26f0348-86a1-45eb-a772-4bb64e18af65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c004b23c-55bf-49ae-9e17-360983fac4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>f3348b9a-0697-4ca9-bf37-0d83546d5fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0feb3e4f-dec3-4793-82e0-b67fe1b2fcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a33e56c3-1ca8-43c2-9e26-ed453bcad8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1fa18058-3ebe-4987-b1c3-b3fdb07876cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter annual leave hour(s)</value>
      <webElementGuid>ba803a6d-a7ec-47ac-b618-61fbeaf7e511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_annualLeaveHours</value>
      <webElementGuid>40e7c89d-3bc6-449e-ada2-9bf3bab06814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>8caf9b35-d92a-46b4-b29f-8281970f3dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>696e417f-1ba4-40e5-bb05-fb1e97a37520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_annualLeaveHours&quot;)</value>
      <webElementGuid>2fb594aa-693f-4b91-93f9-dede2996a2e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_annualLeaveHours']</value>
      <webElementGuid>cae96f0f-7f17-4a86-90d9-c0a77521b1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[4]/div/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>1edf361b-1487-4365-ba69-f2992d852ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>87c740da-d60a-445c-b2d1-c40c83e0a171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please enter annual leave hour(s)' and @id = 'basic_annualLeaveHours']</value>
      <webElementGuid>d9413a1a-9468-4468-8bed-c3577b8575de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
