<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sick Leave Hours_basic_sickLeaveHours</name>
   <tag></tag>
   <elementGuidId>a4f02827-c75a-40b6-ae15-5f0c23371c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_sickLeaveHours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_sickLeaveHours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0a727a4-4d55-46e0-a37e-a93f407064ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5a5a2656-76c8-48e6-bf46-b1ccfd475817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>7f7a1361-3440-4e60-a0ba-7a80316f6d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b53d028-bb9a-4549-9ee4-722c5ab6db7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf8bcb94-b813-47c6-ad79-9f55e19a3555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0ae3250b-ca61-47b3-ad5a-2808251b9308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter sick leave hour(s)</value>
      <webElementGuid>e200ddb1-f039-42d9-bf52-11c5c956da89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_sickLeaveHours</value>
      <webElementGuid>4c025441-8d7c-45fb-a8b1-01ff8b515db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>887027a9-a3d7-48e7-8869-5aa09817dd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>09542131-5323-4b51-a7c3-c3614808a964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_sickLeaveHours&quot;)</value>
      <webElementGuid>e044581e-474a-44ec-9232-b62166f1a5bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_sickLeaveHours']</value>
      <webElementGuid>2271984c-0689-4237-94ef-ba85d9f419bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[4]/div[2]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>b331a23b-586a-4d52-b1fa-b0458026dfdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>b55c300e-a78a-4e67-865d-1acdcb2a05c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please enter sick leave hour(s)' and @id = 'basic_sickLeaveHours']</value>
      <webElementGuid>fab3c4cb-579f-407c-bb16-1e97499976c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
