<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Additional Work Hours_basic_additiona_6f8458</name>
   <tag></tag>
   <elementGuidId>f514d791-999f-4d65-b890-7c927aeb5f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_additionalWorkedHours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_additionalWorkedHours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c4cd0fc-5aa3-49de-bb26-c71780a2ea97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9bcc93cc-6358-49df-a588-ef5073bcc63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>23894880-6e07-4faa-b3d0-8799bd6df9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ae314662-23c5-455e-bff8-279501fb82cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5687829c-90ef-44df-9eec-fb8d9d8cd657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d16449a9-a0f8-4851-bdbe-5532d0ba752e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter additional work hour(s)</value>
      <webElementGuid>0b805e8e-7f55-4488-a6e7-cfe335d98d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_additionalWorkedHours</value>
      <webElementGuid>c2c3d9c0-55e5-4fd5-ac96-6e9604a3d6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>2ae0f62b-2941-4b81-bb95-ad899bd70880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2529db8-9d43-4855-b2e0-69945b450744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_additionalWorkedHours&quot;)</value>
      <webElementGuid>8b8832e3-7442-433a-8622-1fdbf0d9237d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_additionalWorkedHours']</value>
      <webElementGuid>26ee1275-01ca-4fc5-94e1-594353cd5c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[3]/div[2]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>738d0325-e5b1-4d82-87f6-abc7d926b9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>8f7922ae-c77e-4d6c-a1e0-3306c9dbfaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please enter additional work hour(s)' and @id = 'basic_additionalWorkedHours']</value>
      <webElementGuid>9e043078-259d-443e-aa78-699bf26a4007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
