<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MaternalPaternal Leave Hours_basic_ma_60abfd</name>
   <tag></tag>
   <elementGuidId>8266c97d-627f-46b0-8424-fe0dafb00066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_maternalLeaveHours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_maternalLeaveHours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b75f8bc3-3a93-414e-97e6-878cd0fd752e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e4ccf287-bbea-4730-b21b-36283d223c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>e6c769cb-3a86-4a11-bbb6-034ead401993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>496d83dc-3ace-4646-aae3-d244afd913a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a41baff-0e7e-4515-b546-7966c34ec426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7a91c1c7-eb9b-4182-a9e8-6c1d9b2cdc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter maternal leave hour(s)</value>
      <webElementGuid>1e027cb4-da58-4590-a17f-7809de9628eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_maternalLeaveHours</value>
      <webElementGuid>2b4d2302-a3af-4209-adf6-f95bfc410c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>21f98306-0ff9-4215-aaf1-cc82e52fddcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fe9a971f-6f7d-4ee9-8847-8ba92ba3e99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_maternalLeaveHours&quot;)</value>
      <webElementGuid>d5dd9e66-5766-413a-a045-e9765c8e98f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_maternalLeaveHours']</value>
      <webElementGuid>9364fbee-1a54-4d9d-ab30-18ab2b72e0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[5]/div/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>c3689eff-4c5d-4c05-b7f9-dca874c36685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>9cfcc6a8-c246-46dd-b1ad-071e1493f42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please enter maternal leave hour(s)' and @id = 'basic_maternalLeaveHours']</value>
      <webElementGuid>0bc34005-ac94-46c0-9d67-2e9da01605ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
