<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>obj_StatusVaues</name>
   <tag></tag>
   <elementGuidId>b6a559cf-ce12-4aa1-8015-efb679090601</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;filter.employeeStatus_list&quot;]/following-sibling::div[@class=&quot;rc-virtual-list&quot;]//div[@class=&quot;rc-virtual-list-holder-inner&quot;]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
